# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 15:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaNotas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'categoriasnotas',
            },
        ),
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'categorias',
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enderecoEmail', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'email',
            },
        ),
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('nota', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'notas',
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('senha', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.DeleteModel(
            name='Music',
        ),
        migrations.AddField(
            model_name='notas',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='myapp.Usuarios'),
        ),
        migrations.AddField(
            model_name='email',
            name='usuarios_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email', to='myapp.Usuarios'),
        ),
        migrations.AddField(
            model_name='categorianotas',
            name='categorias_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoriasnotas', to='myapp.Categorias'),
        ),
        migrations.AddField(
            model_name='categorianotas',
            name='notas_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Notas'),
        ),
    ]
